otps/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('userdetails.urls', ))
]

userdetails/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'userdetails'

urlpatterns = [
    # /
    url(r'^$', views.UserFormView.as_view(), name='login'),
    url(r'^$', views.logout, name='logout'),
    url(r'^journey/(?P<pk>\d+)/$', login_required(views.journey), name='journey'),
]

userdetails/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=10, unique=True)
    dob = models.DateField(blank=True, null=True)


class Wallet(models.Model):
    user = models.OneToOneField(User)
    wallet_balance = models.FloatField(default=0)


class WalletTransaction(models.Model):
    TRANSACTION_CHOICES = (
        ('Credit', 'Credit'),
        ('Debit', 'Debit'),
    )
    wallet = models.OneToOneField(Wallet)
    transaction_type = models.CharField(max_length=30, choices=TRANSACTION_CHOICES)
    transaction_date_time = models.DateTimeField(default=datetime.now())
    recipient = models.CharField(max_length=300)
    amount = models.FloatField()


class RfidCar(models.Model):
    rfid_no = models.CharField(max_length=20, unique=True)
    number_plate = models.CharField(max_length=10, null=False, unique=True, default="")
    car_name = models.CharField(max_length=20)
    car_type = models.CharField(max_length=20)
    chassis_no = models.CharField(max_length=20)
    issue_date = models.DateField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.chassis_no


class UserRfid(models.Model):
    user = models.ForeignKey(User)
    rfid_no = models.OneToOneField(RfidCar, unique=True)

    def __str__(self):
        return self.rfid_no.rfid_no


class TollPlaza(models.Model):
    toll_name = models.CharField(max_length=100, default="")
    toll_latitude = models.FloatField()
    toll_longitude = models.FloatField()
    three_wheeler_toll = models.IntegerField()
    car_jeep_van_toll = models.IntegerField()
    lcv_minibus_toll = models.IntegerField()
    truck_bus_toll = models.IntegerField()
    heavy_vehicle_toll = models.IntegerField()


class Transaction(models.Model):
    transaction_no = models.CharField(max_length=20)
    rfid_no = models.ForeignKey(RfidCar)
    toll = models.ForeignKey(TollPlaza, default="")
    transaction_date_time = models.DateTimeField(blank=True, null=True)
    amount_paid = models.IntegerField(default=0)
    payment_status = models.BooleanField(default=False)

class Service(models.Model):
    service_name = models.CharField(max_length=50)

class serviceAt(models.Model):
    service = models.ForeignKey(Service)
    tollPlaza = models.ForeignKey(TollPlaza)
    description = models.CharField(max_length = 150)

userdetails/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']

userdetails/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse, render_to_response
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from .forms import UserForm

class UserFormView(View):
    form_class = UserForm
    template_name = 'userdetails/login.html'

    # displaying a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    # processing the form data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            # user = form.save(commit=False)

            # cleaned (normalized) data
            un = form.cleaned_data['username']
            pw = form.cleaned_data['password']
            # user.set_password(pw)

            # returns user objects if credentials are correct
            user = authenticate(username=un, password=pw)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    user_profile = UserProfile.objects.get(user=user)
                    rfid_list = UserRfid.objects.filter(user=user)
                    available_rfids = []
                    for rfid in rfid_list:
                        r = RfidCar.objects.get(rfid_no=str(rfid))
                        available_rfids.append(r)
                    context = {'user':user, 'user_profile':user_profile,'available_rfids':available_rfids}
                    return render(request,'userdetails/dashboard.html',context)
        return render(request, self.template_name, {'form' : form})

def logout(request):
    logout(request)
    form = UserForm(None)
    return render(request, 'userdetails/login.html', {'form': form})


def journey(request, pk):
    r = RfidCar.objects.get(pk=pk)
    return render(request, 'userdetails/journey.html', {'r':r})


def payment(request, pk):
    r = RfidCar.objects.get(pk=pk)
    return render(request, 'userdetails/payment.html', {'r': r})

userdetails/templates/userdetails/company.html
<html>
<head>
<meta charset="utf-8">
        <title>chArt</title>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Char"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<script src="https://www.w3schools.com/lib/w3.js"></script>
</head>
<!-- Uses a transparent header that draws on top of the layout's background -->
<style>
.demo-layout-transparent {
  background: url('../assets/demos/transparent.jpg') center / cover;
}
.demo-layout-transparent .mdl-layout__header,
.demo-layout-transparent .mdl-layout__drawer-button {
  /* This background is dark, so we set text to white. Use 87% black instead if
     your background is light. */
  color: black;
}

</style>

  <!-- Simple header with fixed tabs. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header
            mdl-layout--fixed-tabs">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Company Login</span>
    </div>
    <!-- Tabs -->
    <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
      <a href="#fixed-tab-1" class="mdl-layout__tab is-active">Toll plaza</a>
      <a href="#fixed-tab-2" class="mdl-layout__tab">Revenue</a>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
  </div>
  <main class="mdl-layout__content">
    <section class="mdl-layout__tab-panel is-active" id="fixed-tab-1">
      <div class="page-content"><!-- Your content goes here --> 
      <!-- Expandable Textfield -->
		<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--4-col">
		<form action="#" style="margin-left:5%";>
		  <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
		    <label class="mdl-button mdl-js-button mdl-button--icon" for="sample6">
		      <i class="material-icons">search</i>
		    </label>
		    <div class="mdl-textfield__expandable-holder">
      			<input oninput="w3.filterHTML('#id01', '.item', this.value)" placeholder="Search for toll plaza..">
		      	<label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
		    </div>
		  </div>
		</form>
		
            <table id="id01"class="mdl-data-table mdl-js-data-table" style="margin-left:5%;">
            <tr>
                <th style="width:60%;">Name of the toll PLaza</th>
                <th style="width:40%;">Toll collected</th>
            </tr>
            <!-- for looop from db -->
            <tr class ="item">
                <td>Alfreds Futterkiste</td>
                <td>Germany</td>
            </tr>
            <tr class ="item">
                <td>Tanvi Pandit</td>
                <td>Switzerland</td>
            </tr>
            <tr class ="item">
                <td> Nalini K</td>
                <td>INdia</td>
            </tr>
            <tr class ="item">
                <td>Dacks</td>
                <td>Canada</td>
            </tr>
            <tr class ="item">
                <td> Anubhav</td>
                <td>Germany</td>
            </tr>
            </table>
        	</div>
          <div class="mdl-cell mdl-cell--8-col" >
          	
			    <canvas id="myChart"></canvas>
			</div> 
		  </div>
        

    </section>
    <section class="mdl-layout__tab-panel" id="fixed-tab-2">
      <div class="page-content"><!-- Your content goes here --></div>
    </section>
    

	<script>
	var ctx = document.getElementById("myChart");
	//ctx.height = ;
	//ctx.canvas.width  = 100 ;
 	var myChart = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday","Sunday"],
	        datasets: [{
	            label: '# Collection',
	            data: [12, 19, 3, 5, 2, 3,1],
	            borderColor: [
	                'rgba(255,255,255,0)',
	                'rgba(255,255,255,0)',
	                'rgba(255,255,255,0)',
	                'rgba(255,255,255,0)',
	                'rgba(255,255,255,0)',
	                'rgba(255,255,255,0)',

	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero:true
	                }
	            }]
	        }
	    }
	});
	</script>
  </main>
</div>
  
  
  
  
  

userdetails/templates/userdetails/dashboard.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<title></title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'userdetails/teal-green.css' %}" />
	<script src="{% static 'userdetails/material.min.js' %}"></script>
	<style type="text/css">
		@font-face {
  			font-family: 'Material Icons';
  			font-style: normal;
  			font-weight: 400;
  			src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v21/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
		}
		.material-icons {
  			font-family: 'Material Icons';
  			font-weight: normal;
  			font-style: normal;
  			font-size: 24px;
  			line-height: 1;
  			letter-spacing: normal;
  			text-transform: none;
  			display: inline-block;
  			white-space: nowrap;
  			word-wrap: normal;
  			direction: ltr;
            -webkit-font-feature-settings: 'liga';
            -webkit-font-smoothing: antialiased;
        }

    .mdl-button.mdl-js-button{
      background-color: #F5F5F5;
      width: 60%;
      height: auto;
      margin-bottom: 1em;
      margin-top: 1em;
      -webkit-transition: box-shadow 0.3s; /* Safari */
      transition: box-shadow 0.3s;
      padding: 0;
    }
    .mdl-button.mdl-js-button:hover{
      box-shadow: 0 8px 10px 1px rgba(0, 0, 0, .14), 0 3px 14px 2px rgba(0, 0, 0, .12), 0 5px 5px -3px rgba(0, 0, 0, .2);
    }

    .wrapper{
      margin: 0 auto;
      width: 40em;
      padding: 0;
    }
	</style>
</head>
<body>
<!-- Always shows a header, even in smaller screens. -->
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  		<header class="mdl-layout__header">
    		<div class="mdl-layout__header-row">
      			<!-- Title -->
      			<span class="mdl-layout-title">Tolle</span>
      			<!-- Add spacer, to align navigation to the right -->
      			<div class="mdl-layout-spacer"></div>
      			<!-- Navigation. We hide it in small screens. -->
    		</div>
  		</header>
  	<div class="mdl-layout__drawer">
    	<span class="mdl-layout-title">Dashboard</span>
    	<nav class="mdl-navigation">
      		<a class="mdl-navigation__link" href="">Refill Wallet</a>
      		<a class="mdl-navigation__link" href="">Recipt</a>
      		<a class="mdl-navigation__link" href="">Services</a>
      		<a class="mdl-navigation__link" href="{% url 'userdetails:logout' %}">Logout</a>
    	</nav>
  </div>

  <main class="mdl-layout__content" style="background-color: #E0F7FA">

    <div class="demo-card-wide mdl-card mdl-shadow--2dp mdl-grid center-items" style="width: 70%; margin-top: 1%; padding: 0 0 1em 0">
        <header style="margin-bottom: 0.2em; background-color: #80DEEA; width: 100%; height: 40px; padding-top: 5px; padding-bottom: 0; padding-left: 5px; box-shadow: 0px 4px 3px rgbda(0,0,0,.14);">
                <span style="color: white; font-family: Arial; font-size: 150%; margin: 0">Welcome {{ user.first_name }}</span>
        </header>
        <br>
	    {% for rfid in available_rfids %}
            <a type="submit" href="{% url 'userdetails:journey' pk=rfid.pk %}" value="{{ rfid.car_name }}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-grid center-items">
                <div style="padding: 0; font-size: 120%; display: block;" class="mdl-grid center-items">
                    <span style="font-size: 160%; display: block;">{{ rfid.car_name }}</span>
                    <hr style="margin-bottom: 0px; margin-top: 0.5em">
                <span style="display: block; padding-top: 0px; margin-top: 0px">{{ rfid.number_plate }}</span>
                </div>
            </a>
	    {% endfor %}
    </div>
  </main>

</body>
</html>

userdetails/templates/userdetails/journey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start Your Journey</title>
</head>
<body>
    <h1>{{ r.car_name }}</h1>
</body>
</html>

userdetails/templates/userdetails/login.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	{% load staticfiles %}
    {% load widget_tweaks %}
	<link rel="stylesheet" type="text/css" href="{% static 'userdetails/teal-green.css' %}" />
	<script src="{% static 'userdetails/material.min.js' %}"></script>
	<style type="text/css">
		@font-face {
  			font-family: 'Material Icons';
  			font-style: normal;
  			font-weight: 400;
  			src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v21/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
		}

		.material-icons {
  			font-family: 'Material Icons';
  			font-weight: normal;
  			font-style: normal;
  			font-size: 24px;
  			line-height: 1;
  			letter-spacing: normal;
  			text-transform: none;
  			display: inline-block;
  			white-space: nowrap;
  			word-wrap: normal;
  			direction: ltr;
            -webkit-font-feature-settings: 'liga';
            -webkit-font-smoothing: antialiased;
        }
	</style>
</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--no-drawer-button">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Tolle</span>
    </div>
  </header>
  <main class="mdl-layout__content">
    <div class="page-content">
    	<div style="position: relative; height: 5em"></div>
    	<div class="mdl-card mdl-shadow--4dp mdl-grid center-items">
        <div class="mdl-card__media" style="margin: 0 auto; background-color: transparent;">
          <img src="{% static 'userdetails/logo.png' %}" height="100%" width="auto" border="0" alt="" style="margin-top: 0; margin-bottom: 0; background-color: transparent;">
        </div>
  			<div class="mdl-card__title" style="padding: 0; margin: 0 auto;">
    			<h4>Login</h4>
  			</div>
  			<form action="" method="post">
			{% csrf_token %}
  				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {% render_field form.username class+="mdl-textfield__input" style+="width: 90%; margin: 0 auto; padding-left: 0; padding-right: 0; padding-bottom: 0"%}
                    <!--pattern="-?[0-9]*(\.[0-9]+)?"-->
    				<label class="mdl-textfield__label" for="sample4" style="width: 90%; margin: 0 auto;">{{ form.username.label_tag }}</label>
  				</div>
  				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
  					{% render_field form.password class+="mdl-textfield__input" style+="width: 90%; margin: 0 auto; padding-left: 0; padding-right: 0; padding-bottom: 0" %}
                    <!--pattern="-?[0-9]*(\.[0-9]+)?"-->
    				<label class="mdl-textfield__label" for="sample4" style="width: 90%; margin: 0 auto;">{{ form.password.label_tag }}</label>
  				</div>
  				<div class="mdl-layout-spacer"></div>
  				<div class="mdl-grid center-items">
  					<button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="margin: 0 auto">
  						Login
					</button>
				</div>
  			</form>
		</div>
    </div>
  </main>
</div>	
</body>
</html>

userdetails/templates/userdetails/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment</title>
</head>
<body>
    <h4>{{ r.rfid_no }}</h4>
    <button >
</body>
</html>